name: toucanet
description: Simple vk client

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2+1
  url_launcher: ^5.4.5
  video_player: ^0.10.9+1
  chewie_audio: ^1.0.0+1
  audio_service: ^0.7.2
  photo_view: ^0.9.2

  bloc: ^4.0.0
  rxdart: ^0.24.0
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0

  flutter_keychain: ^1.0.0
  cached_network_image: ^2.2.0
  flutter_webview_plugin: ^0.3.10+2
  device_info: ^0.4.2+2
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.2
  sqflite: ^1.3.0

  isolate_supervisor: ^1.0.1+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - config/
    - assets/icons/
