name: toucanet
description: Simple vk client

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^1.1.0
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2+1

  bloc: ^3.0.0
  equatable: ^1.1.1 
  flutter_bloc: ^3.2.0

  flutter_keychain: ^1.0.0
  cached_network_image: ^2.0.0
  flutter_webview_plugin: ^0.3.10+2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - config/
    - assets/icons/
