name: toucanet
description: Simple vk client

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  webview_flutter: ^0.3.14+1
  cached_network_image: ^2.0.0
  shimmer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
